version: "3"
# volumes:
#   aem-data:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none

services:
  aem-author:
    image: pawangonnakuti/aem-author:latest
    ports:
      - 4502:4040
    volumes:
      - ./config:/opt/aem-config
      - ./logs:/opt/aem/ctx-quickstart/logs
    healthcheck:
      test: "exit 0"

  aem-publish:
    image: pawangonnakuti/aem-publish:latest
    ports:
      - 4503:4040
    volumes:
      - ./config:/opt/aem-config
      - ./logs:/opt/aem/ctx-quickstart/logs
    healthcheck:
      test: "exit 0"
